### ISSUE TITLE
Doesn't build with GCC 5.1.x

### ISSUE THREAD

**Issue by prokoudine** [mtytel/helm#58]
Fedora 23 uses GCC 5.1.1 which appears to enforce C++11:

make[1]: Entering directory '/home/alex/soft/sound/lv2/helm/standalone/builds/linux'
Linking Helm
build/intermediate/Release/load_save_2c95b2e1.o: In function `LoadSave::loadControls(mopo::HelmEngine*, juce::CriticalSection const&, juce::NamedValueSet const&)':
load_save.cpp:(.text+0xb6b): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
load_save.cpp:(.text+0xbc2): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
load_save.cpp:(.text+0xe54): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
load_save.cpp:(.text+0xeb0): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/load_save_2c95b2e1.o: In function `LoadSave::loadConfig(MidiManager*, mopo::StringLayout*)':
load_save.cpp:(.text+0x1a7b): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/load_save_2c95b2e1.o: In function `LoadSave::stateToVar(mopo::HelmEngine*, juce::CriticalSection const&, juce::String)':
load_save.cpp:(.text+0x24ff): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/load_save_2c95b2e1.o: In function `LoadSave::saveConfig(MidiManager*, mopo::StringLayout*)':
load_save.cpp:(.text+0x33a2): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/startup_52cb2a28.o: In function `Startup::fixPatchesFolder()':
startup.cpp:(.text+0x35e): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/startup_52cb2a28.o: In function `Startup::updateAllPatches(mopo::HelmEngine*, juce::CriticalSection const&)':
startup.cpp:(.text+0x68f): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/graphical_step_sequencer_763b67a0.o: In function `GraphicalStepSequencer::showRealtimeFeedback()':
graphical_step_sequencer.cpp:(.text+0x106f): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/modulation_button_8258c889.o: In function `ModulationButton::mouseDown(juce::MouseEvent const&)':
modulation_button.cpp:(.text+0x287): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
modulation_button.cpp:(.text+0x363): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/synth_slider_ab0cf9a.o: In function `SynthSlider::getTextFromValue(double)':
synth_slider.cpp:(.text+0x265): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/synth_slider_ab0cf9a.o: In function `SynthSlider::SynthSlider(juce::String)':
synth_slider.cpp:(.text+0x7c6): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0x81e): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0x916): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/synth_slider_ab0cf9a.o: In function `SynthSlider::notifyTooltip()':
synth_slider.cpp:(.text+0xb59): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0xbc2): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/synth_slider_ab0cf9a.o: In function `SynthSlider::mouseDown(juce::MouseEvent const&)':
synth_slider.cpp:(.text+0xd19): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0xe24): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0xe95): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0xf3f): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
synth_slider.cpp:(.text+0x11dd): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_slider.cpp:(.text+0x1261): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/synth_slider_ab0cf9a.o: In function `SynthSlider::mouseUp(juce::MouseEvent const&)':
synth_slider.cpp:(.text+0x146c): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/wave_viewer_e4b5610c.o: In function `WaveViewer::showRealtimeFeedback()':
wave_viewer.cpp:(.text+0x1071): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
wave_viewer.cpp:(.text+0x10ab): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/envelope_section_a35a0a34.o: In function `EnvelopeSection::EnvelopeSection(juce::String, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
envelope_section.cpp:(.text+0x9fd): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
envelope_section.cpp:(.text+0xad6): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
envelope_section.cpp:(.text+0xba9): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
envelope_section.cpp:(.text+0xc7c): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
envelope_section.cpp:(.text+0xdea): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/lfo_section_f85fa167.o:lfo_section.cpp:(.text+0x8ea): more undefined references to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
build/intermediate/Release/modulation_manager_a5602c68.o: In function `ModulationManager::setSliderValues()':
modulation_manager.cpp:(.text+0x500): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/modulation_manager_a5602c68.o: In function `ModulationManager::ModulationManager(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mopo::Processor::Output*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mopo::Processor::Output*> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ModulationButton*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ModulationButton*> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, SynthSlider*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, SynthSlider*> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mopo::Processor::Output*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mopo::Processor::Output*> > >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mopo::Processor::Output*, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mopo::Processor::Output*> > >)':
modulation_manager.cpp:(.text+0x1532): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
modulation_manager.cpp:(.text+0x164f): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/modulation_manager_a5602c68.o: In function `ModulationManager::buttonClicked(juce::Button*)':
modulation_manager.cpp:(.text+0x27be): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/modulation_manager_a5602c68.o: In function `ModulationManager::sliderValueChanged(juce::Slider*)':
modulation_manager.cpp:(.text+0x29f8): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/patch_browser_b6fb73fd.o: In function `PatchBrowser::scanPatches()':
patch_browser.cpp:(.text+0x12f1): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/save_section_1a7d8ce1.o: In function `SaveSection::save()':
save_section.cpp:(.text+0x702): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
save_section.cpp:(.text+0x89d): undefined reference to `juce::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
build/intermediate/Release/synth_section_3b1ee2e.o: In function `SynthSection::buttonClicked(juce::Button*)':
synth_section.cpp:(.text+0x475): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/synth_section_3b1ee2e.o: In function `SynthSection::sliderValueChanged(juce::Slider*)':
synth_section.cpp:(.text+0x5b5): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/synth_section_3b1ee2e.o: In function `SynthSection::addButton(juce::Button*, bool)':
synth_section.cpp:(.text+0xaee): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
synth_section.cpp:(.text+0xbce): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/synth_section_3b1ee2e.o: In function `SynthSection::addModulationButton(ModulationButton*, bool)':
synth_section.cpp:(.text+0xd9e): undefined reference to `juce::String::toStdString[abi:cxx11]() const'
build/intermediate/Release/synth_section_3b1ee2e.o:synth_section.cpp:(.text+0xe7e): more undefined references to `juce::String::toStdString[abi:cxx11]() const' follow
collect2: error: ld returned 1 exit status
Makefile:170: recipe for target 'build/helm' failed
make[1]: *** [build/helm] Error 1
make[1]: Leaving directory '/home/alex/soft/sound/lv2/helm/standalone/builds/linux'
Makefile:21: recipe for target 'standalone' failed
make: *** [standalone] Error 2

I tried the only trick in the book I know, namely, 

$ CXXFLAGS="-std=c++11" make

Unfortunately, still no fun.

**Comment by mtytel** [comment]
I wonder why it's having a problem linking with JUCE..
Also not sure how to repro this.

**Comment by mtytel** [comment]
After a little research it looks like the problem might be that the JUCE files were built with a version of GCC before 5.1. https://bugs.gentoo.org/show_bug.cgi?id=536984

Did you `make clean` before building? There could also be a bug in my Makefile and something is being left uncleaned..

**Comment by prokoudine** [comment]
Oh blast, that was it. Thanks, Matt! You are amazing :)
